<!DOCTYPE html>
<html>
    <head>
        <title>Iniciar Sesion</title>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="CSS3/estiloscabezera.css">
        <link rel="icon" type="Imagenes/png" href="Imagenes/Logo_Empresa.png">
        <link rel="stylesheet" type="text/css" href="CSS3/footer.css">

    </head>
    <body>
        <nav class="main-header">

            <container>
                <div id= "logo-header">
                    <span class="site-name">Crumble&Flake.com</span>
                    <span class="site-desc">Pasteles / Postres / Bocaditos</span>
                </div>

                <div class="nav_menu">
                    <ul >
                        <li><a href="index.html"><img src="https://getconnected.honeywellhome.com/en/sites/getconnected.honeywell.com.en/files/lyric_to_home.png" height="18" width="18" style="vertical-align: middle;"> Home</a></li>
                        <li><a href="Comprar.html"><img src="https://icones.pro/wp-content/uploads/2021/05/icone-de-panier-noir.png" width="20" height="20" style="vertical-align: middle;"> Comprar</a></li>
                        <li><a href="Carrito.html"><img src="Imagenes/carrito.png" width="40" height="40" style="vertical-align: middle;"> Carrito</a></li>
                        <li><a href="eleccion_sesion.html"><button class="nav--button" href="#">Iniciar sesión</button></a></li>                        
                    </ul>
                </div>
            </container>
        </nav>

        <div class="general">
            <div class="logo-ses">
                <span class="site-imag"><img src="Imagenes/cook.svg" ></span>
            </div>

            <br><br>
            <div class = "tipo">
                <h2 align="center">Seleccion el tipo de ingreso:</h2>
                <section class="eleccion sesion">
                    <br>

                    <div class="ico-sesi">

                        <div class="sesio">
                            <a href="Ingresar_Usuario.html"><img src="https://dewey.tailorbrands.com/production/brand_version_mockup_image/427/4304447427_54b254de-3fb5-41ed-827d-d020b37f66b3.png?cb=1608158588"></a>
                        </div>

                        <div class="sesio">
                            <a href="Ingresar_Administrador.html"><img src="https://dewey.tailorbrands.com/production/brand_version_mockup_image/729/4304502729_46f79922-6135-4070-b18d-d3778a3ddf86.png?cb=1608159206"></a>
                        </div>

                    </div>

                </section>
            </div>
        </div>


        <br><br>
        <br><br>
        <br><br><br>

        <footer class="footer-section">

            <div class="copyright-area">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 text-center text-lg-left">
                            <div class="copyright-text">
                                <p>Copyright &copy; 2022, All Right Reserved <a href="index.html">Crumble&Flake</a></p>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 d-none d-lg-block text-right">
                            <div class="footer-menu">
                                <ul>
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">Terminos</a></li>
                                    <li><a href="#">Privacidad</a></li>
                                    <li><a href="#">Política</a></li>
                                    <li><a href="#">Contacto</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>


    </body>
</html>