<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Registrate</title>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="CSS3/estiloscabezera.css">
        <link rel="icon" type="Imagenes/png" href="Imagenes/Logo_Empresa.png">
        <link rel="stylesheet" type="text/css" href="CSS3/footer.css">

    </head>
    <body>

        <nav class="main-header">
            <container>
                <div id= "logo-header">
                    <span class="site-name">Crumble&Flake.com</span>
                    <span class="site-desc">Pasteles / Postres / Bocaditos</span>
                </div>

                <div class="nav_menu">
                    <ul >
                        <li><a href="index.PHP"><img src="https://getconnected.honeywellhome.com/en/sites/getconnected.honeywell.com.en/files/lyric_to_home.png" height="18" width="18" style="vertical-align: middle;"> Home</a></li>

                        <li><a href="Comprar.PHP"><img src="https://icones.pro/wp-content/uploads/2021/05/icone-de-panier-noir.png" width="20" height="20" style="vertical-align: middle;"> Comprar</a></li>

                        <li><a href="Carrito.PHP"><img src="Imagenes/carrito.png" width="40" height="40" style="vertical-align: middle;"> Carrito</a></li>
                        <li><a href="eleccion_sesion.PHP"><button class="nav--button" href="#">Iniciar sesión</button></a></li>


                    </ul>



            </container>


        </nav>


        <br><br>
        <span class="site-imag"><img src="https://dewey.tailorbrands.com/production/brand_version_mockup_image/97/7762432097_b09238fc-346a-4194-832f-663753e6878e.png?cb=1662436924" height="250" width="300"></span>

        <table align="center">

            <tr>
                <th>

                    <div>	
                        <form class="formulario">
                            <fieldset>

                                <div class="form-group">
                                    <input type="text" name="usuario" placeholder="Usuario">
                                </div>

                                <div>
                                    <input type="password" name="password" placeholder="Contraseña">
                                </div>

                                <div class="form-group">

                                    <input type="password" name="password2" placeholder="Confirmar Contraseña">
                                    <br><br>
                                    <button type="button">Registrate</button>
                                </div>
                        </form>

                        <p>
                            ¿Ya tienes cuenta? <br>
                            <a href="Ingresar_Usuario.PHP">Iniciar Sesión</a>
                        </p>

                    </div>

                    </fieldset>
                    </form>	
                </th>

                <th>
                    <img src="https://dewey.tailorbrands.com/production/brand_version_mockup_image/217/3837693217_4c05142e-8d8c-4b2d-bfd5-cdc81cd77690.png?cb=1601574946" width="300" height="300"> 
                </th>
            </tr>

        </table>

        <br><br>
        <br><br>
        <br><br><br>

        <footer class="footer-section">

            <div class="copyright-area">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 text-center text-lg-left">
                            <div class="copyright-text">
                                <p>Copyright &copy; 2022, All Right Reserved <a href="index.PHP">Crumble&Flake</a></p>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 d-none d-lg-block text-right">
                            <div class="footer-menu">
                                <ul>
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">Terminos</a></li>
                                    <li><a href="#">Privacidad</a></li>
                                    <li><a href="#">Política</a></li>
                                    <li><a href="#">Contacto</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>       


    </body>
</html>